version: "3.5"
services:
    traefik:
        image: traefik:v2.3.6
        environment:
            TZ: Asia/Bangkok
        ports:
            - "80:80"        
            - "8080:8080"               
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.whoami.address=:80"
        volumes:            
            - /var/run/docker.sock:/var/run/docker.sock:ro
    whoami:
        image: "traefik/whoami"
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.routers.whoami.entrypoints=whoami"
            - "traefik.tcp.routers.whoami.rule=HostSNI(`*`)"    
            - "traefik.tcp.routers.whoami.service=whoami-service"            
            - "traefik.tcp.services.whoami-service.loadbalancer.server.port=80"    
