version: "3.5"
services:
    traefik:
        image: traefik:v2.3.6
        environment:
            TZ: Asia/Bangkok
        ports:
            - "80:80"        
            - "8080:8080"               
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.whoami.address=:80"
        volumes:            
            - /var/run/docker.sock:/var/run/docker.sock:ro
    whoami1:
        image: "traefik/whoami"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
            - "traefik.http.routers.whoami.service=whoami-service"
            - "traefik.http.services.whoami-service.loadbalancer.server.port=80"            
                       
    whoami2:
        image: "traefik/whoami"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
            - "traefik.http.routers.whoami.service=whoami-service"
            - "traefik.http.services.whoami-service.loadbalancer.server.port=80"
        